vim.cmd([[set cursorline]])

require('vimscript')
require('plugins')
require('config')
require('treesitter_config')
require('toggleterm_config')
require('gitsigns_config')
require('comment_config')
require('luasnip_config')
require('options')
require('keymaps')
require('dartvim')
require('colorscheme')
